### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by nuqz** [tkrajina/go-reflector#3]
Hi, @tkrajina. I've noticed you're using plain tests instead of benchmarks for checking performance, is there a reason for that?. I think the results are completely wrong. There should not be any checks, but only "getting/setting values" and functions calls should be. Also, I think that if you want to compare your package's performance with pure Go's performance, it would be a good choice to explicitly compare GetTags method with getting tags with pure reflect ( there's no other way to get struct tags).

**Comment by tkrajina** [comment]
Yes, I agree with you, but this is just a rough estimate. Anyway, if somebody is willing to fix it, I'll accept a PR.
