### ISSUE TITLE
你好，可以写一个反射嵌套对象的例子吗?

### ISSUE THREAD

**Issue by DiskGetor** [tkrajina/go-reflector#4]
我正在写一个protobuf V2版本不需要.proto协议文件的库，类似这样的结构，我想一次性反射它以便于编码：

type ( //?
	Group1 struct {
		binary1 string
		packed2 Packed2
		varint3 uint64
		binary4 string
		varint5 uint64
	}
	Packed2 struct {
		group2  []Group2
		binary3 string
	}
	Group2 struct {
		varint1 uint64
		binary2 string
		binary3 string
		binary4 string
	}
)

func testNestedGroup() {
	a := &Group1{
		binary1: "game/system/session/info",
		packed2: Packed2{
			group2: []Group2{
				{
					varint1: 0,
					binary2: "d3048a459417e6c0b7d39c971b99a58029f2720f7b2a70c992c826ce48184069",
					binary3: "6593D03B-92BC-4BC6-BF54-D16BB0271AF9",
					binary4: "Apple-iPhone10,3",
				},
				{
					varint1: 1,
					binary2: "",
					binary3: "EAAIe5YPC68wBAPGE5l7JEtIE9BfPQmbcpQ92b0c9fD29vKn5ZCwHkutEjpX2PEcvyBLDqo15gNi1x0VN7U6d26QDaABEDaVzu3vuZBYKtvHH130O9Kna4742s6B8dtr1aKJUw7HuuyNWObpWYZCqBDGvypB7Js93oBISkwWrjbuYZAooY5vHLHFPyuIcLAcV8ZAX9sRFn3un18KZA0MEuDtgekU4ZBTJ1doEQmQ4DCLXwZDZD",
					//binary4: "",
				},
			},
			binary3: "6593D03B-92BC-4BC6-BF54-D16BB0271AF9",
		},
		varint3: 0,
		binary4: "",
		varint5: 0,
	}

	b := NewBuffer(nil)
 嵌套对象为objGroup和ObjPacked

**Comment by tkrajina** [comment]
I don't know Chinese, so I'll reply in Croatian:

Ako ne griješim - ovo nije prijava greške u ovoj knjižnici nego molba za pomoć u riješavanje konkretnog problema. Web stranice poput stackoverflowa su puno bolje mjesto za pitanja o tome kako nešto isprogramirati.

Lijep pozdrav,
tk
